[project]
name = "jirahours"
version = "0.1.0"
description = "A over-engineered python script to move hours from CSV to Jira."
authors = [
    {name = "Mikko Kuokkanen", email = "mikko.kuokkanen@gmail.com"}
]
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "click (==8.3.0)",
    "httpx (==0.28.1)",
    "python-dotenv (==1.1.1)"
]

[project.scripts]
jirahours = "jirahours.main:start"

[tool.poetry.group.dev.dependencies]
black = "25.9.0"
isort = "6.1.0"
pytest = "8.4.2"
pytest-cov = "7.0.0"
mypy = "1.18.2"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"
files = ["src", "tests"]
strict = "True"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
